# List automatically applied labels by GitHub Labeler.
#
# See configuration in ``.github/workflows/labeller.yml``.
#
build:
- changed-files:
  - any-glob-to-any-file:
    - setup.py
    - setup.cfg
    - .pyproject.toml
    - .pyproject_cuda.toml
    - Makefile
    - MANIFEST.in
    - deploy/pkg/**/*
    - .github/workflows/ci*.yml
    - .github/workflows/cd*.yml

documentation:
- changed-files:
  - any-glob-to-any-file:
    - docs/**/*
    - README.*
    - CHANGELOG.*
    - CITATION.*
    - deploy/doc/**/*
    - .readthedocs.yaml

maintenance:
- changed-files:
  - any-glob-to-any-file:
    - setup.py
    - setup.cfg
    - .pyproject.toml
    - .pyproject_cuda.toml
    - Makefile
    - MANIFEST.in
    - NOTES.md
    - deploy/test/**/*
    - .github/**/*.md

workflows:
- changed-files:
  - any-glob-to-any-file:
    - deploy/**/*
    - .pre-commit-config.yaml
    - .readthedocs.yaml
    - .github/**/*.yml
