# List automatically applied labels by GitHub Labeler.
#
# See configuration in ``.github/workflows/labeller.yml``.
#
build:
- changed-files:
  - any-glob-to-any-files:
    - setup.py
    - setup.cfg
    - pyproject.toml
    - Makefile
    - MANIFEST.in
    - .github/workflows/ci*.yml
    - .github/workflows/cd*.yml

documentation:
- changed-files:
  - any-glob-to-any-files:
    - docs/**/*
    - deploy/doc/**/*
    - README.*
    - .readthedocs.yml

maintenance:
- changed-files:
  - any-glob-to-any-files:
    - .github/**/*.md
    - CHANGELOG.md
    - NOTES.md

workflows:
- changed-files:
  - any-glob-to-any-files:
    - .github/**/*.yml
    - deploy/**/*
