# Deploy Dependabot for dependency update checks.
#
# See documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
#
version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "[dependabot] "
    labels:
      - 'maintenance'
    assignees:
      - MikeSWang

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "[dependabot] "
    labels:
      - 'workflows'
    assignees:
      - MikeSWang
    reviewers:
      - MikeSWang
