version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.8'
  apt_packages:
    - libgsl-dev
    - libfftw3-dev
  jobs:
    pre_build:
      - make pyinstall useomp=true
      - bash docs/gendocs.sh

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/dependencies.txt
    - method: pip
      path: .
  system_packages: true
