version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.8'
  apt_packages:
    - libgsl-dev
    - libfftw3-dev
  jobs:
    pre_build:
      - python -m pip install --verbose --editable .
      - bash docs/gendocs.sh
    post_build:
      - rm docs/source/Doxyfile
      - echo $(ls -l ${READTHEDOCS_OUTPUT})
      - mv ${READTHEDOCS_OUTPUT}/_static/apiref_doxy/ \
            ${READTHEDOCS_OUTPUT}/
      - mkdir -p ${READTHEDOCS_OUTPUT}/apiref_doxy/docs/source/_static/
      - find ./source/_static/ -maxdepth 1 -type f -exec cp {} \
            ${READTHEDOCS_OUTPUT}/apiref_doxy/docs/source/_static/

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/dependencies.txt
    - method: pip
      path: .
  system_packages: true
