version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.8'
  apt_packages:
    - libgsl-dev
    - libfftw3-dev
  jobs:
    pre_build:
      - python -m pip install --verbose --editable .
      - bash docs/gendocs.sh
    post_build:
      - echo ${READTHEDOCS_OUTPUT}
      - find $(pwd) -type d -print
      - rm docs/source/Doxyfile
      - >
        mv ${READTHEDOCS_OUTPUT}/html/_static/apiref_doxy/
           ${READTHEDOCS_OUTPUT}/html/
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/
      - >
        find docs/source/_static/ -maxdepth 1 -type f
          -exec cp {}
          ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/ \;

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/dependencies.txt
    - method: pip
      path: .
  system_packages: true
