version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.8'
  apt_packages:
    - libgsl-dev
    - libfftw3-dev
    - graphviz
  jobs:
    pre_build:
      - pip install --editable . -vvv
      - bash deploy/doc/autogen_docs.sh
    post_build:
      - rm docs/source/Doxyfile
      - >
        mv
        ${READTHEDOCS_OUTPUT}/html/_static/apiref_doxy/
        ${READTHEDOCS_OUTPUT}/html/
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/
      - >
        find docs/source/_static/ -maxdepth 1 -type f -exec cp
        {} ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/ \;

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/dependencies.txt
    - method: pip
      path: .
  system_packages: true
