version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.8'
  apt_packages:
    - libfftw3-dev

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/dependencies.txt
    - method: pip
      path: .
  system_packages: true
