version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: miniconda-latest
  apt_packages:
    - libgsl-dev
    - libfftw3-dev
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --all --tags || true
    pre_create_environment:
      - conda update --yes --quiet --name=base --channel=defaults conda
    post_create_environment:
      - conda list
    pre_install:
      - git update-index --assume-unchanged docs/environment.yml docs/source/conf.py
    pre_build:
      - pip install --editable . -vvv
      - bash deploy/doc/autogen_docs.sh
    post_build:
      - rm docs/source/Doxyfile
      - >
        mv
        ${READTHEDOCS_OUTPUT}/html/_static/apiref_doxy/
        ${READTHEDOCS_OUTPUT}/html/
      - mkdir -p ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/
      - >
        find docs/source/_static/ -maxdepth 1 -type d -exec cp -r
        {} ${READTHEDOCS_OUTPUT}/html/apiref_doxy/docs/source/_static/ \;

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/environment.yml

# python:
#   install:
#     - requirements: docs/dependencies.txt
#     - method: pip
#       path: .
