name: trv-dev
category: dev
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - python >=3.10
  - pip >=22.0
  - setuptools >=61.0
  - setuptools_scm >=6.4
  - cython >=3.0
  - extension-helpers >=1.1
  - gsl >=2.7
  - fftw >=3.3
  - libgomp
  - llvm-openmp
  - hdf5
  - pkg-config
  # Runtime dependencies
  - numpy >=1.23
  - scipy >=1.13
  - sympy >=1.12.1
  - astropy >=4.2
  - pyyaml >=5.1
  - mpi4py >=3.1.5
  - tqdm
  # Test dependencies
  - pre-commit >=3.7
  - pytest >=7.0
