# Provide continuous delivery (CD) for arm64-based target platforms
# from (non-native) build platforms.
#
# CD deliverables currently include:
# - (non-natively) built Python wheel distributions (for PyPI);
# - (non-natively) built conda packages (for Anaconda).
#
name: continuous-delivery-arm64

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+.post[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    paths:
      - deploy/pkg/conda_recipe_arm64/**
      - .github/workflows/cd_arm64.yml
  workflow_dispatch:
    inputs:
      run_build_bdist_arm64:
        description: 'Run job build_bdist_arm64'
        type: boolean
        default: false
        required: false
      run_build_conda_arm64:
        description: 'Run job build_conda_arm64'
        type: boolean
        default: false
        required: false
      version_tag:
        description: 'Version tag for delivery'
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_bdist_arm64:
    name: Build bdist wheel (arm64)

    strategy:
      fail-fast: false
      matrix:
        # Use oldest supported OS for backward compatibility.
        os: [ubuntu-20.04, macos-11]
        # Skip non-arm64 macOS runner (as cross compilation is not working).
        exclude:
          - os: macos-11

    runs-on: ${{ matrix.os }}

    timeout-minutes: 180

    if: >
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.run_build_bdist_arm64 == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Use QEMU for non-arm64 Linux runner.
      - name: Set up QEMU (Linux)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          # Specify arm64 architecture.
          platforms: linux/arm64

      - name: Install packaging requirements
        run: python -m pip install --upgrade twine

      - name: Build built distribution
        uses: pypa/cibuildwheel@v2.13.1
        with:
          package-dir: .
          output-dir: dist_arm64/
          config-file: pyproject.toml
        env:
          # Optional: Specify arm64 architecture (as non-native).
          CIBW_ARCHS_LINUX: aarch64
          CIBW_ARCHS_MACOS: arm64
          # Default to LLVM compiler and OpenMP on macOS.
          CIBW_ENVIRONMENT_MACOS: >-
            PY_CXX=$(brew --prefix llvm)/bin/clang++
            PY_CXXFLAGS="-I$(brew --prefix)/include"
            PY_LDFLAGS="-L$(brew --prefix)/lib"
            PY_CXXFLAGS_OMP="-Xpreprocessor -fopenmp"
            PY_LDFLAGS_OMP="-L$(brew --prefix libomp)/lib -lomp"

      - name: Verify built distribution
        uses: knicknic/os-specific-run@v1.0.4
        with:
          # BUG: ``twine check`` fails to recognise ``--strict`` on macOS.
          linux: python -m twine check --strict dist_arm64/*
          macos: python -m twine check dist_arm64/*

      - name: Save wheel to bdist
        uses: actions/upload-artifact@v3
        with:
          name: bdist_wheel_arm64_${{ github.ref_name }}
          path: dist_arm64/*.whl

      - name: Save wheel to pypi_dist
        uses: actions/upload-artifact@v3
        with:
          name: pypi_dist_arm64_${{ github.ref_name }}
          path: dist_arm64/*.whl

  build_conda_arm64:
    name: Build conda package (arm64)

    strategy:
      fail-fast: false
      matrix:
        # Use oldest supported OS for backward compatibility.
        os: [ubuntu-20.04, macos-11]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 180

    # Skip as no native arm64 runner exists.
    if: >
      github.event_name != 'workflow_dispatch' && false ||
      github.event.inputs.run_build_conda_arm64 == 'true'

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up (Mini)conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda_bld
          channels: conda-forge
          channel-priority: strict
          # # Specify arm64 architecture.
          # architecture: ARM64

      - name: Configure conda environment
        uses: knicknic/os-specific-run@v1.0.4
        with:
          # Specify arm64 architecture.
          linux: conda config --env --set subdir linux-aarch64
          macos: conda config --env --set subdir osx-arm64

      - name: Install packaging requirements
        run: |
          conda install -y conda-build conda-verify conda-package-handling
          # `cph` not found otherwise.
          conda_root=$(conda config --show root_prefix | sed 's/root_prefix: //')
          conda_env=${conda_root}/envs/conda_bld
          export PATH=$PATH:${conda_root}/bin:${conda_env}/bin

      - name: Override version
        if: github.event_name == 'workflow_dispatch'
        uses: knicknic/os-specific-run@v1.0.4
        env:
          recipe_file: deploy/pkg/conda_recipe_arm64/meta.yaml
        with:
          linux: |
            vers_tag=${{ github.event.inputs.version_tag }}
            if [[ ! -z ${vers_tag} ]]; then
              sed -i "s/# git_rev:.*/git_rev: ${vers_tag}/g" ${recipe_file}
            fi
          macos: |
            vers_tag=${{ github.event.inputs.version_tag }}
            if [[ ! -z ${vers_tag} ]]; then
              sed -i '' "s/# git_rev:.*/git_rev: ${vers_tag}/g" ${recipe_file}
            fi

      - name: Build conda package
        env:
          recipe_dir: deploy/pkg/conda_recipe_arm64
          output_dir: dist_arm64/
          variants: "{'python': ['3.8', '3.9', '3.10']}"
        run: |
          # Create output directory if non-existent.
          if [[ ! -d ${output_dir} ]]; then mkdir -p ${output_dir}; fi
          # Build.
          conda-build --strict-verify --no-anaconda-upload ${recipe_dir} \
            --variants "${variants}" --output-folder ${output_dir}
          # Transmute.
          find ${output_dir} -name "*.tar.bz2" \
            -exec cph transmute {} .conda --out-folder ${output_dir} \;

      - name: Save build to conda_bld
        uses: actions/upload-artifact@v3
        with:
          name: conda_bld_arm64_${{ github.ref_name }}
          path: dist_arm64/*

      - name: Save build to conda_dist
        uses: actions/upload-artifact@v3
        with:
          name: conda_dist_arm64_${{ github.ref_name }}
          path: |
            dist_arm64/**/*.tar.bz2
            dist_arm64/*.conda
