name: continuous-integration

on:
  push:
    branches:
      - main
      - 'v[0-9]+'
    paths:
      - src/**
      - tests/**
      - setup.py
      - setup.cfg
      - pyproject.toml
      - MANIFEST.in
      - Makefile
      - .gitignore
      - .github/workflows/ci.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-dev:
    name: Build & test (in dev mode)

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, llvm]
        exclude:
          - os: ubuntu-latest
            compiler: llvm

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python build system requirements
        run: python -m pip install --upgrade pip

      - name: Install C++ build dependency requirements
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: |
            sudo apt-get update
            sudo apt-get install -y libgsl-dev libfftw3-dev
          macos: |
            # Optional command: Homebrew update is slow.
            # brew update
            # Optional command: GitHub runner runtime exceptions.
            brew reinstall llvm libomp
            brew install gsl fftw

      - name: Build and install (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: make clean; make -j -O install useomp=true

      - name: Build and install (macOS with GCC)
        if: matrix.os == 'macos-latest' && matrix.compiler == 'gcc'
        run: |
          CXX_DIR=$(brew --prefix gcc)/bin
          CXX_BIN=$(ls ${CXX_DIR} | grep '^g++')
          export CXX=${CXX_DIR}/${CXX_BIN}
          make clean; make -j install useomp=true

      - name: Build and install (macOS with LLVM)
        if: matrix.os == 'macos-latest' && matrix.compiler == 'llvm'
        run: |
          CXX_DIR=$(brew --prefix llvm)/bin
          CXX_BIN=clang++
          export CXX=${CXX_DIR}/${CXX_BIN}
          export CXXFLAGS="${CXXFLAGS} -Xpreprocessor"
          export LDFLAGS_OMP="-L$(brew --prefix libomp)/lib -lomp"
          export ARCHFLAGS="-arch x86_64"
          make clean; make -j install useomp=true

      - name: Install Python test requirements
        run: python -m pip install --upgrade pytest

      - name: Test
        run: pytest

  lint:
    name: Lint

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python linting requirements
        run: python -m pip install flake8

      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --statistics
