name: distribution

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  test-pypi:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python packaging system requirements
        run: python -m pip install --upgrade build auditwheel

      - name: Install C++ build required dependencies
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: |
            sudo apt-get update
            sudo apt-get install -y libgsl-dev libfftw3-dev libgomp1
          macos: |
            brew update
            brew install gsl fftw libomp

      - name: Build distribution(s)
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Forge wheels
        run: auditwheel -v repair dist/*.whl

      - name: Upload distribution(s) to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
