name: JOSS publication

on:
  push:
    branches:
      - main
    paths:
      - publication/joss/**
      - .github/workflows/publication-joss.yml

jobs:
  compile-joss:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # Input path to the draft file 'paper.md' within the repo.
          paper-path: publication/joss/paper.md
      - name: Upload draft PDF
        uses: actions/upload-artifact@v1
        with:
          name: paper
          # Output path to the PDF file 'paper.pdf', which should be in
          # the same directory as the draft .md file and is where Pandoc
          # writes the compiled PDF.
          path: publication/joss/paper.pdf
